### ISSUE TITLE
Using `aws-native:profile` results in an error - failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds

### ISSUE THREAD

**Issue by janaka** [pulumi/registry#1803]
Following doesn't work 

File: [themes/default/content/registry/packages/aws-native/installation-configuration.md](https://www.pulumi.com/registry/packages/aws-native/installation-configuration/)

>After creating your project, run pulumi config set aws-native:profile <profilename>

If the config file _only_ has `aws-native:profile: <profilename>` then I get the following error.

If the config file has `aws:profile: <profilename>` the `pulumi up` runs without an error.

OS: macOS 12.3.1
Pulumi CLI: v3.48
Project: AWS + TypeScript

```sh
View Live: https://app.pulumi.com/janaka/pulumi-sample/dev/previews/cd5eb90f-7a7d-4cfb-92ee-151662957cc7

     Type                 Name               Plan       Info
 +   pulumi:pulumi:Stack  pulumi-sample-dev  create     12 messages
     └─ aws:ecs:Cluster   cluster                       1 error


Diagnostics:
  pulumi:pulumi:Stack (pulumi-sample-dev):
    error: [runtime] Running program '/Users/janakaabeywardhana/code-projects/fabr/pulumi-sample' failed with an unhandled exception:
    Error: failed to register new resource loadbalancer [awsx:lb:ApplicationLoadBalancer]: Resource monitor is terminating
        at Object.registerResource (/Users/janakaabeywardhana/code-projects/fabr/pulumi-sample/node_modules/@pulumi/runtime/resource.ts:294:27)
        at new Resource (/Users/janakaabeywardhana/code-projects/fabr/pulumi-sample/node_modules/@pulumi/resource.ts:402:13)
        at new ComponentResource (/Users/janakaabeywardhana/code-projects/fabr/pulumi-sample/node_modules/@pulumi/resource.ts:895:9)
        at new ApplicationLoadBalancer (/Users/janakaabeywardhana/code-projects/fabr/pulumi-sample/node_modules/@pulumi/lb/applicationLoadBalancer.ts:92:9)
        at Object.<anonymous> (/Users/janakaabeywardhana/code-projects/fabr/pulumi-sample/index.ts:22:22)
        at Module._compile (node:internal/modules/cjs/loader:1205:14)
        at Module.m._compile (/Users/janakaabeywardhana/code-projects/fabr/pulumi-sample/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/janakaabeywardhana/code-projects/fabr/pulumi-sample/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (node:internal/modules/cjs/loader:1068:32)

  aws:ecs:Cluster (cluster):
    error: unable to validate AWS credentials.
    Details: no valid credential sources for  found.
    
    Please see
    for more information about providing credentials.
    
    Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: i/o timeout
```

**Comment by janaka** [comment]
Thanks for the response. Can you please point out the difference in setup for AWSx pls?

<img width="657" alt="image" src="https://user-images.githubusercontent.com/51779/206746707-93b1465a-5af2-49c0-8317-55e93e7309a2.png">

It looks identical in the [link](https://www.pulumi.com/registry/packages/awsx/installation-configuration/#configuration) you shared.

I'm brand new to Pulumi (like one day in :) ) I understand the high-level difference between Classic and AWSx but not at this level.

**Comment by roothorp** [comment]
Of course, my apologies!

[AWSx](https://www.pulumi.com/registry/packages/awsx/) is a layer on top of the existing [AWS 'Classic'](https://www.pulumi.com/registry/packages/aws/) resources to help with best practices and ease of common tasks. Therefore, when using AWSx, the configuration is the same as if you were using AWS Classic (which is documented [here](https://www.pulumi.com/registry/packages/aws/installation-configuration/#configuration-options)), with `pulumi config set aws:<option>`.

[AWS Native](https://www.pulumi.com/registry/packages/aws-native/) is a seperate provider to AWS Classic, which uses the Cloud Control API rather than the AWS SDK. This is configured with `pulumi config set aws-native:<option>`. The doc you linked in the initial issue is for AWS Native; if you're just using AWSx, you shouldn't have to use this - just configuring AWS Classic should be sufficient.

Please let me know if I can help any more!

**Comment by janaka** [comment]
Ah ok, so my understanding wasn't accurate. I thought AWSx = Native provider. 

Can you link me the docs for the native providers so I can understand coverage?
